# https://chromewebstore.google.com/detail/fngmhnnpilhplaeedifhccceomclgfbg
import json

def json_to_cookies_txt(json_file_path, cookies_txt_path):
    # Load JSON data from file
    with open(json_file_path, 'r') as json_file:
        cookies = json.load(json_file)

    # Write cookies to cookies.txt format
    with open(cookies_txt_path, 'w') as cookies_file:
        cookies_file.write("# Netscape HTTP Cookie File\n")
        cookies_file.write("# This file was generated by a Python script.\n")

        for cookie in cookies:
            # Extract fields from JSON
            domain = cookie.get('domain', '')
            host_only = 'FALSE' if not cookie.get('hostOnly', False) else 'TRUE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expiration = int(cookie.get('expirationDate', 0))
            name = cookie.get('name', '')
            value = cookie.get('value', '')

            # Write to file in cookies.txt format
            cookies_file.write(f"{domain}\t{host_only}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

# Specify the path to the JSON file and the output cookies.txt file
json_file_path = 'cookies.json'
cookies_txt_path = 'cookies.txt'

# Convert JSON to cookies.txt format
json_to_cookies_txt(json_file_path, cookies_txt_path)
